sudo: required
services:
  - docker

before_install:
  - docker build -t thanh829/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true thanh829/react-test npm test

after_success:
  - docker build -t thanh829/multi-client ./client
  - docker build -t thanh829/multi-server ./server
  - docker build -t thanh829/multi-nginx ./nginx
  - docker build -t thanh829/multi-worker ./worker
  # Login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin
  # Push image to docker hub
  - docker push thanh829/multi-client
  - docker push thanh829/multi-server
  - docker push thanh829/multi-nginx
  - docker push thanh829/multi-worker